// ⚠️ Substitua pelo número real de WhatsApp (somente números, com DDI)
export const WHATSAPP_NUMBER = '5571996860176'
export const WHATSAPP_MESSAGE = 'Olá! Vim pelo site e gostaria de saber mais sobre os produtos da Ótica Pague Menos. 😊'
export const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`

export const STORE_INFO = {
  name: 'Ótica Pague Menos',
  tagline: 'Veja o mundo da melhor forma',
  // ⚠️ Substitua pelas informações reais
  address: 'Shopping Piedade, Loja 45',
  street: 'Rua Junqueira Ayres, 165',
  neighborhood: 'Piedade, Salvador — BA',
  cep: 'CEP: 40415-000',
  phone: '(71) 9 9686-0176',
  email: 'contato@oticapaguemenos.com.br',
  instagram: 'https://www.instagram.com/oticapaguemenos.oficial/',
  hours: [
    { days: 'Segunda a Sábado', time: '9h às 20h' },
  ],
  mapsEmbed: 'https://maps.google.com/maps?q=Rua+Junqueira+Ayres+165+Piedade+Salvador+Bahia&t=m&z=17&output=embed&iwloc=near',
  mapsLink: 'https://maps.google.com/maps?q=Rua+Junqueira+Ayres+165+Piedade+Salvador+Bahia',
}

export const BRANDS = [
  "V'Gaspari", 'Eagle', 'Fênix', 'Ray-Ban',
  'Tommy Hilfiger', 'Pierre Cardin', 'Polaroid', 'Carrera',
]

export const FEATURED_PRODUCTS = [1, 2, 3, 4]

export const PRODUCTS = [
  // — Destaques originais —
  {
    id: 1,
    name: 'Cat Eye Elegance',
    category: 'Feminino',
    description: 'Design contemporâneo com toque clássico',
    price: null,
    image: '/imagens/swappy-20260327_114625.png',
    tag: 'Destaque',
    tagColor: 'brand-yellow',
  },
  {
    id: 2,
    name: 'Browline Dourado Premium',
    category: 'Unissex',
    description: 'Elegância e sofisticação em detalhes dourados',
    price: null,
    image: '/imagens/swappy-20260327_114446.png',
    tag: 'Novo',
    tagColor: 'green-500',
  },
  {
    id: 3,
    name: 'Retangular Sport Edition',
    category: 'Masculino',
    description: 'Estilo moderno para o dia a dia',
    price: null,
    image: '/imagens/swappy-20260327_114555.png',
    tag: null,
    tagColor: null,
  },
  {
    id: 4,
    name: 'Classic Square Collection',
    category: 'Unissex',
    description: 'Clássico e atemporal para todas as ocasiões',
    price: null,
    image: '/imagens/swappy-20260327_114603.png',
    tag: 'Promoção',
    tagColor: 'red-500',
  },
  {
    id: 5,
    name: 'Grande Frame Contemporâneo',
    category: 'Feminino',
    description: 'Armação oversized de alto impacto',
    price: null,
    image: '/imagens/swappy-20260327_114434.png',
    tag: null,
    tagColor: null,
  },

  // — Feminino —
  { id: 6,   name: 'Armação Feminina 01',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 1.png',   tag: null, tagColor: null },
  { id: 7,   name: 'Armação Feminina 02',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino2.png',    tag: null, tagColor: null },
  { id: 8,   name: 'Armação Feminina 03',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 3.png',   tag: null, tagColor: null },
  { id: 9,   name: 'Armação Feminina 04',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 4.png',   tag: null, tagColor: null },
  { id: 10,  name: 'Armação Feminina 05',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 5.png',   tag: null, tagColor: null },
  { id: 11,  name: 'Armação Feminina 06',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 6.png',   tag: null, tagColor: null },
  { id: 12,  name: 'Armação Feminina 07',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 7.png',   tag: null, tagColor: null },
  { id: 13,  name: 'Armação Feminina 08',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 8.png',   tag: null, tagColor: null },
  { id: 14,  name: 'Armação Feminina 09',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 9.png',   tag: null, tagColor: null },
  { id: 15,  name: 'Armação Feminina 10',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 10.png',  tag: null, tagColor: null },
  { id: 16,  name: 'Armação Feminina 11',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 11.png',  tag: null, tagColor: null },
  { id: 17,  name: 'Armação Feminina 12',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 12.png',  tag: null, tagColor: null },
  { id: 18,  name: 'Armação Feminina 13',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 13.png',  tag: null, tagColor: null },
  { id: 19,  name: 'Armação Feminina 14',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 14.png',  tag: null, tagColor: null },
  { id: 20,  name: 'Armação Feminina 15',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 15.png',  tag: null, tagColor: null },
  { id: 21,  name: 'Armação Feminina 16',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 16.png',  tag: null, tagColor: null },
  { id: 22,  name: 'Armação Feminina 17',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos femino 17.png',   tag: null, tagColor: null },
  { id: 23,  name: 'Armação Feminina 18',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 18.png',  tag: null, tagColor: null },
  { id: 24,  name: 'Armação Feminina 19',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 19.png',  tag: null, tagColor: null },
  { id: 25,  name: 'Armação Feminina 20',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 20.png',  tag: null, tagColor: null },
  { id: 26,  name: 'Armação Feminina 21',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 21.png',  tag: null, tagColor: null },
  { id: 27,  name: 'Armação Feminina 22',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos femini no 22.png', tag: null, tagColor: null },
  { id: 28,  name: 'Armação Feminina 23',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 23.png',  tag: null, tagColor: null },
  { id: 29,  name: 'Armação Feminina 24',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 24.png',  tag: null, tagColor: null },
  { id: 30,  name: 'Armação Feminina 25',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 25.png',  tag: null, tagColor: null },
  { id: 31,  name: 'Armação Feminina 26',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 26.png',  tag: null, tagColor: null },
  { id: 32,  name: 'Armação Feminina 27',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 27.png',  tag: null, tagColor: null },
  { id: 33,  name: 'Armação Feminina 28',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos 28.png',           tag: null, tagColor: null },
  { id: 34,  name: 'Armação Feminina 29',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos 29.png',           tag: null, tagColor: null },
  { id: 35,  name: 'Armação Feminina 30',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos 30.png',           tag: null, tagColor: null },
  { id: 36,  name: 'Armação Feminina 31',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos f 31.png',         tag: null, tagColor: null },
  { id: 37,  name: 'Armação Feminina 32',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos 32.png',           tag: null, tagColor: null },
  { id: 38,  name: 'Armação Feminina 33',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos f 33.png',         tag: null, tagColor: null },
  { id: 39,  name: 'Armação Feminina 34',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos f34.png',          tag: null, tagColor: null },
  { id: 40,  name: 'Armação Feminina 35',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos f 35.png',         tag: null, tagColor: null },
  { id: 41,  name: 'Armação Feminina 36',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 36.png',  tag: null, tagColor: null },
  { id: 42,  name: 'Armação Feminina 37',  category: 'Feminino', description: 'Estilo e elegância para o dia a dia', price: null, image: '/imagens/oculos feminino 37.png',  tag: null, tagColor: null },
  { id: 43,  name: 'Armação Feminina 38',  category: 'Feminino', description: 'Sofisticação em cada detalhe',          price: null, image: '/imagens/oculos feminino 38.png',  tag: null, tagColor: null },

  // — Masculino —
  { id: 44,  name: 'Armação Masculina 01', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/Masc 1.png',    tag: null, tagColor: null },
  { id: 45,  name: 'Armação Masculina 02', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 2.png',    tag: null, tagColor: null },
  { id: 46,  name: 'Armação Masculina 03', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/msc 3.png',     tag: null, tagColor: null },
  { id: 47,  name: 'Armação Masculina 04', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 4.png',    tag: null, tagColor: null },
  { id: 48,  name: 'Armação Masculina 05', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 5.png',    tag: null, tagColor: null },
  { id: 49,  name: 'Armação Masculina 06', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 6.png',    tag: null, tagColor: null },
  { id: 50,  name: 'Armação Masculina 07', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 7.png',    tag: null, tagColor: null },
  { id: 51,  name: 'Armação Masculina 08', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 8.png',    tag: null, tagColor: null },
  { id: 52,  name: 'Armação Masculina 09', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 9.png',    tag: null, tagColor: null },
  { id: 53,  name: 'Armação Masculina 10', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 10.png',   tag: null, tagColor: null },
  { id: 54,  name: 'Armação Masculina 11', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 11.png',   tag: null, tagColor: null },
  { id: 55,  name: 'Armação Masculina 12', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/massc 12.png',  tag: null, tagColor: null },
  { id: 56,  name: 'Armação Masculina 13', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/mASC 13.png',   tag: null, tagColor: null },
  { id: 57,  name: 'Armação Masculina 14', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 14.png',   tag: null, tagColor: null },
  { id: 58,  name: 'Armação Masculina 15', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 15.png',   tag: null, tagColor: null },
  { id: 59,  name: 'Armação Masculina 16', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 16.png',   tag: null, tagColor: null },
  { id: 60,  name: 'Armação Masculina 17', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 17.png',   tag: null, tagColor: null },
  { id: 61,  name: 'Armação Masculina 18', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 18.png',   tag: null, tagColor: null },
  { id: 62,  name: 'Armação Masculina 19', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/mac 19.png',    tag: null, tagColor: null },
  { id: 63,  name: 'Armação Masculina 20', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 20.png',   tag: null, tagColor: null },
  { id: 64,  name: 'Armação Masculina 21', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 21.png',   tag: null, tagColor: null },
  { id: 65,  name: 'Armação Masculina 22', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 22.png',   tag: null, tagColor: null },
  { id: 66,  name: 'Armação Masculina 23', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 23.png',   tag: null, tagColor: null },
  { id: 67,  name: 'Armação Masculina 24', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 24.png',   tag: null, tagColor: null },
  { id: 68,  name: 'Armação Masculina 25', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 25.png',   tag: null, tagColor: null },
  { id: 69,  name: 'Armação Masculina 26', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 26.png',   tag: null, tagColor: null },
  { id: 70,  name: 'Armação Masculina 27', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 27.png',   tag: null, tagColor: null },
  { id: 71,  name: 'Armação Masculina 28', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 28.png',   tag: null, tagColor: null },
  { id: 72,  name: 'Armação Masculina 29', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 29.png',   tag: null, tagColor: null },
  { id: 73,  name: 'Armação Masculina 30', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 30.png',   tag: null, tagColor: null },
  { id: 74,  name: 'Armação Masculina 31', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 31.png',   tag: null, tagColor: null },
  { id: 75,  name: 'Armação Masculina 32', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 32.png',   tag: null, tagColor: null },
  { id: 76,  name: 'Armação Masculina 33', category: 'Masculino', description: 'Robustez e estilo moderno',           price: null, image: '/imagens/masc 33.png',   tag: null, tagColor: null },
  { id: 77,  name: 'Armação Masculina 34', category: 'Masculino', description: 'Design arrojado e confortável',       price: null, image: '/imagens/masc 34.png',   tag: null, tagColor: null },

  // — Infantil —
  { id: 78,  name: 'Armação Infantil 01',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 1.png',  tag: null, tagColor: null },
  { id: 79,  name: 'Armação Infantil 02',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 2.png',  tag: null, tagColor: null },
  { id: 80,  name: 'Armação Infantil 03',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 3.png',  tag: null, tagColor: null },
  { id: 81,  name: 'Armação Infantil 04',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 4.png',  tag: null, tagColor: null },
  { id: 82,  name: 'Armação Infantil 05',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 5.png',  tag: null, tagColor: null },
  { id: 83,  name: 'Armação Infantil 06',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 6.png',  tag: null, tagColor: null },
  { id: 84,  name: 'Armação Infantil 07',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 7.png',  tag: null, tagColor: null },
  { id: 85,  name: 'Armação Infantil 08',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 8.png',  tag: null, tagColor: null },
  { id: 86,  name: 'Armação Infantil 09',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 9.png',  tag: null, tagColor: null },
  { id: 87,  name: 'Armação Infantil 10',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 10.png', tag: null, tagColor: null },
  { id: 88,  name: 'Armação Infantil 11',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 11.png', tag: null, tagColor: null },
  { id: 89,  name: 'Armação Infantil 12',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 12.png', tag: null, tagColor: null },
  { id: 90,  name: 'Armação Infantil 13',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 13.png', tag: null, tagColor: null },
  { id: 91,  name: 'Armação Infantil 14',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 14.png', tag: null, tagColor: null },
  { id: 92,  name: 'Armação Infantil 15',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 15.png', tag: null, tagColor: null },
  { id: 93,  name: 'Armação Infantil 16',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 16.png', tag: null, tagColor: null },
  { id: 94,  name: 'Armação Infantil 17',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 17.png', tag: null, tagColor: null },
  { id: 95,  name: 'Armação Infantil 18',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/in 18.png',  tag: null, tagColor: null },
  { id: 96,  name: 'Armação Infantil 19',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 19.png', tag: null, tagColor: null },
  { id: 97,  name: 'Armação Infantil 20',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 20.png', tag: null, tagColor: null },
  { id: 98,  name: 'Armação Infantil 21',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 21.png', tag: null, tagColor: null },
  { id: 99,  name: 'Armação Infantil 22',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 22.png', tag: null, tagColor: null },
  { id: 100, name: 'Armação Infantil 23',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 23.png', tag: null, tagColor: null },
  { id: 101, name: 'Armação Infantil 24',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 24.png', tag: null, tagColor: null },
  { id: 102, name: 'Armação Infantil 25',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 25.png', tag: null, tagColor: null },
  { id: 103, name: 'Armação Infantil 26',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 26.png', tag: null, tagColor: null },
  { id: 104, name: 'Armação Infantil 27',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 27.png', tag: null, tagColor: null },
  { id: 105, name: 'Armação Infantil 28',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 28.png', tag: null, tagColor: null },
  { id: 106, name: 'Armação Infantil 29',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 29.png', tag: null, tagColor: null },
  { id: 107, name: 'Armação Infantil 30',  category: 'Infantil', description: 'Perfeita para os pequenos',            price: null, image: '/imagens/inf 30.png', tag: null, tagColor: null },
  { id: 108, name: 'Armação Infantil 31',  category: 'Infantil', description: 'Leve, colorida e resistente',          price: null, image: '/imagens/inf 31.png', tag: null, tagColor: null },
]
